In [1]:
#House_Prediction using more than one independent variable (Multiple Linear Regression)

from sklearn.linear_model import LinearRegression
import pandas as pd

In [8]:
df = pd.read_csv('House_price_2.csv')
df.sample(5)
# df.keys()

Area_in_m2  Price_in_L  Bedrooms
10        1800        90.0         3
5         1325        80.1         3
9          960        89.0         3
0          656        39.0         2
4         1800       140.0         3

In [6]:
model = LinearRegression()
model.fit(df[['Area_in_m2', 'Bedrooms']], df['Price_in_L'])

LinearRegression()

In [9]:
model.predict([[1500, 3]])

C:\Users\yuvra\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([103.19350085])

In [10]:
test = pd.DataFrame([
    {'Area_in_m2':1500, 'Bedrooms':2},
    {'Area_in_m2':1500, 'Bedrooms':3}
])

In [11]:
model.predict(test)

array([ 69.2400953 , 103.19350085])

In [12]:
model.coef_

array([2.67199301e-02, 3.39534056e+01])

In [13]:
model.intercept_

np.float64(-38.74661096694119)